
import { UserProfile } from '../types';

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: '1',
    name: 'Ananya Sharma',
    email: 'ananya@example.com',
    mobileNumber: '+91 98765 43210',
    gender: 'Female',
    age: 26,
    height: "5'4\"",
    dateOfBirth: '1998-05-14',
    maritalStatus: 'Never Married',
    motherTongue: 'Hindi',
    religion: 'Hindu',
    caste: 'Brahmin',
    city: 'New Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    education: 'MBA in Finance',
    college: 'Delhi University',
    occupation: 'Investment Banker',
    industry: 'Banking',
    income: '20-25 LPA',
    nriStatus: 'Resident',
    lifestyle: ['Vegetarian', 'Non-smoker', 'Occasional Drinker'],
    familyBackground: 'Nuclear family with modern values. Father is a retired Govt officer, mother is a homemaker.',
    familyValues: 'Moderate',
    familyType: 'Nuclear',
    familyStatus: 'Upper Middle Class',
    bio: 'Looking for a compatible partner who values career and family balance. I enjoy traveling and classical music.',
    photoUrl: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&q=80&w=400&h=500',
    additionalPhotos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=500',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400&h=500'
    ],
    isVerified: true,
    isPremium: true,
    isDemo: true,
    lastActive: 'Active now',
    joinedDate: '2024-01-10',
    role: 'user',
    status: 'active',
    moderationStatus: 'approved',
    declarationAccepted: true,
    declarationTimestamp: '2024-01-10T10:00:00Z',
    partnerPreferences: {
      ageRange: '26 - 32',
      heightRange: "5'7\" - 6'2\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      motherTongue: 'Hindi, Punjabi',
      education: 'Masters or above',
      occupation: 'Professional / Corporate',
      location: 'Delhi NCR or Overseas'
    }
  },
  {
    id: '2',
    name: 'Rahul Verma',
    email: 'rahul@example.com',
    mobileNumber: '+91 98765 43211',
    gender: 'Male',
    age: 29,
    height: "5'11\"",
    dateOfBirth: '1995-08-22',
    maritalStatus: 'Never Married',
    motherTongue: 'Punjabi',
    religion: 'Sikh',
    caste: 'Jat',
    city: 'Chandigarh',
    district: 'Chandigarh',
    state: 'Punjab',
    country: 'India',
    education: 'B.Tech CS',
    college: 'IIT Delhi',
    occupation: 'Software Engineer',
    industry: 'IT',
    income: '45-50 LPA',
    nriStatus: 'Resident',
    lifestyle: ['Non-vegetarian', 'Non-smoker', 'Non-drinker'],
    familyBackground: 'Joint family, agricultural background with focus on education. Both parents are teachers.',
    familyValues: 'Traditional',
    familyType: 'Joint',
    familyStatus: 'Middle Class',
    bio: 'Tech enthusiast, love traveling and exploring new cultures. Looking for someone grounded.',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400&h=500',
    additionalPhotos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=500'
    ],
    isVerified: true,
    isPremium: false,
    isDemo: true,
    lastActive: 'Active 2h ago',
    joinedDate: '2024-02-15',
    role: 'user',
    status: 'active',
    moderationStatus: 'approved',
    declarationAccepted: true,
    declarationTimestamp: '2024-02-15T12:00:00Z',
    partnerPreferences: {
      ageRange: '23 - 28',
      heightRange: "5'2\" - 5'7\"",
      maritalStatus: 'Never Married',
      religion: 'Sikh',
      motherTongue: 'Punjabi',
      education: 'Bachelors or above',
      occupation: 'Any',
      location: 'North India'
    }
  },
  {
    id: '3',
    name: 'Priya Iyer',
    email: 'priya@example.com',
    mobileNumber: '+91 98765 43212',
    gender: 'Female',
    age: 27,
    height: "5'5\"",
    dateOfBirth: '1997-03-30',
    maritalStatus: 'Never Married',
    motherTongue: 'Tamil',
    religion: 'Hindu',
    caste: 'Brahmin',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    education: 'M.S. Data Science',
    college: 'Anna University',
    occupation: 'Data Scientist',
    industry: 'Analytics',
    income: '30-35 LPA',
    nriStatus: 'Resident',
    lifestyle: ['Vegetarian', 'Non-smoker', 'Non-drinker'],
    familyBackground: 'Traditional family with deep cultural roots. Father is a scientist at ISRO.',
    familyValues: 'Moderate',
    familyType: 'Nuclear',
    familyStatus: 'Upper Middle Class',
    bio: 'Passionate about classical music and data storytelling. Seeking an intellectual partner.',
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0ad2f01?auto=format&fit=crop&q=80&w=400&h=500',
    isVerified: true,
    isPremium: true,
    isDemo: true,
    lastActive: 'Active 5m ago',
    joinedDate: '2023-11-20',
    role: 'user',
    status: 'active',
    moderationStatus: 'approved',
    declarationAccepted: true,
    declarationTimestamp: '2023-11-20T09:00:00Z',
    partnerPreferences: {
      ageRange: '27 - 33',
      heightRange: "5'8\" - 6'1\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      motherTongue: 'Tamil, English',
      education: 'Masters / Doctorate',
      occupation: 'Academic / Tech',
      location: 'Chennai / Bangalore / USA'
    }
  },
  {
    id: '4',
    name: 'Arjun Reddy',
    email: 'arjun@example.com',
    mobileNumber: '+91 98765 43213',
    gender: 'Male',
    age: 31,
    height: "5'10\"",
    dateOfBirth: '1993-11-12',
    maritalStatus: 'Never Married',
    motherTongue: 'Telugu',
    religion: 'Hindu',
    caste: 'Reddy',
    city: 'Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    education: 'MD Cardiology',
    college: 'Osmania Medical College',
    occupation: 'Doctor',
    industry: 'Healthcare',
    income: '60+ LPA',
    nriStatus: 'Resident',
    lifestyle: ['Non-vegetarian', 'Non-smoker', 'Occasional Drinker'],
    familyBackground: 'Father is a businessman, mother is a homemaker. Well established family in Hyderabad.',
    familyValues: 'Moderate',
    familyType: 'Nuclear',
    familyStatus: 'Affluent',
    bio: 'Dedicated professional seeking someone with a kind heart and similar values.',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=500',
    isVerified: false,
    isPremium: false,
    isDemo: true,
    lastActive: 'Active yesterday',
    joinedDate: '2024-03-01',
    role: 'user',
    status: 'active',
    moderationStatus: 'approved',
    declarationAccepted: true,
    declarationTimestamp: '2024-03-01T15:30:00Z',
    partnerPreferences: {
      ageRange: '24 - 29',
      heightRange: "5'3\" - 5'8\"",
      maritalStatus: 'Never Married',
      religion: 'Hindu',
      motherTongue: 'Telugu',
      education: 'Medical / Professional',
      occupation: 'Any',
      location: 'Telangana / Andhra'
    }
  },
  {
    id: '5',
    name: 'Siddharth Mehta',
    email: 'siddharth@example.com',
    mobileNumber: '+91 98765 43214',
    gender: 'Male',
    age: 28,
    height: "5'9\"",
    dateOfBirth: '1996-01-05',
    maritalStatus: 'Never Married',
    motherTongue: 'Gujarati',
    religion: 'Jain',
    caste: 'Vaishya',
    city: 'New York',
    district: 'Manhattan',
    state: 'NY',
    country: 'USA',
    education: 'Master in Management',
    college: 'Columbia University',
    occupation: 'Product Manager',
    industry: 'Tech',
    income: '$150k - $200k',
    nriStatus: 'NRI',
    lifestyle: ['Vegan', 'Non-smoker', 'Non-drinker'],
    familyBackground: 'Upper middle class, values Jain principles. Family settled in Ahmedabad.',
    familyValues: 'Liberal',
    familyType: 'Nuclear',
    familyStatus: 'Rich',
    bio: 'Looking for a life partner settled in US or willing to move. I enjoy hiking and tech startups.',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400&h=500',
    isVerified: true,
    isPremium: true,
    isDemo: true,
    lastActive: 'Active now',
    joinedDate: '2024-02-28',
    role: 'user',
    status: 'active',
    moderationStatus: 'approved',
    declarationAccepted: true,
    declarationTimestamp: '2024-02-28T18:45:00Z',
    partnerPreferences: {
      ageRange: '24 - 28',
      heightRange: "5'2\" - 5'7\"",
      maritalStatus: 'Never Married',
      religion: 'Jain / Hindu',
      motherTongue: 'Gujarati',
      education: 'Masters',
      occupation: 'Tech / Management',
      location: 'USA'
    }
  }
];
